### ISSUE TITLE
Suggestion - move to multiprocessing library

### ISSUE THREAD

**Issue by darachm** [FangfeiLi05/FitSeq#12]
I believe the python3 standard `multiprocessing` library offers similar functionality for Pool.map as does
the `multiprocess` library used here.

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map

Moving to a more standard, and by default installed library, would be good for maintenance, debugging, and stability
of the software.

**Comment by FangfeiLi05** [comment]
Yes, they should be very similar. I use `multiprocess` instead of `multiprocessing`, because `multiprocessing`  doesn't work in my computer for some unknown reason. And I check online, people report similar problem as mine, the solution they propose is to use `multiprocess` as a replacement. That's why I use `multiprocess`.

**Comment by darachm** [comment]
Do you think it's an issue with python2.7 being installed?

**Comment by darachm** [comment]
Resolved in https://github.com/darachm/PyFitSeq
Containers also (somewhat) available
